name: CI

on: { push: {}, pull_request: {} }

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend   # 👈 change le dossier par défaut

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm --filter users test
      - run: pnpm --filter todo test
      - run: pnpm --filter pokemon test
      - run: pnpm --filter gateway test
