name: CI Backend
on:
  push: { paths: [ "backend/**", ".github/workflows/ci-backend.yml" ] }
  pull_request: { paths: [ "backend/**", ".github/workflows/ci-backend.yml" ] }

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          # ⚠️ on enlève le "cache: pnpm" car il attend un lockfile

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm --filter users test
      - run: pnpm --filter todo test
      - run: pnpm --filter pokemon test
      - run: pnpm --filter gateway test
